- src/components/common-btn.html
> 💄style: Create btn component

- src/components/main-card-item.html
> 💄style: Create main-card-item component

- src/components/common-footer.html
- Add temporary footer markup and CSS
- Apply responsive layout for mobile (under 768px)
> 💄style: Create common-footer component

- src/components/common-input.html
> 💄style: Create common-input component

- src/components/project-card-item.html
- Implement card section markup and responsive layout
> 💄style: Create project-card-item component

- src/components/project-intro-card.html
- Implemented project page mention logic
- Added responsive mobile layout
> 💄style: Create project intro section

- src/pages/project-page.html
- Created /src/pages/project-page.html for project section layout
- Added /src/js/project-page.js for related logic handling
> ✨ feat: Add project page markup and script files

- index.html
각 컴포넌트/페이지로 이동할 수 있게 index.html에 링크 추가
resolves #27
> :sparkles: feat: Implement page change from index page

- index.html
- package-lock.json
- package.json
- src/components/feed-card-item.html
- src/js/feed-card-item.js
> :sparkles: feat: Implement feed-card-item UI component

- index.html
- src/components/project-popview.html
> :sparkles: feat: Implement project-popview UI component

- index.html
> :whale: chore: add project-page in index

- src/js/main-page.js
> ✨ feat: Add mainpage wheel-event

- src/components/feed-card-item.html
- src/js/feed-page.js
- src/pages/feed-page.html
> :sparkles: Add modal in feed-page

- src/js/main-card-img.js
- src/pages/main-page.html
- src/style.css
> Feature/main page/tab slider

- src/pages/mypage-page.html
> :lipstick: style: Center profile info in mypage

- src/js/mypage-page.js
- src/pages/mypage-page.html
- src/style.css
> :sparkles: feat: Add function to show notice modal when deleting account

- src/js/project-page.js
- src/pages/project-page.html
> Refactor/project modal markup(2)

- src/js/main-card-img.js
- src/js/main-card-item.js
- src/pages/main-page.html
- src/style.css
> 💄style/main page/section5

- src/pages/login-page.html
> 💄 style: Change Font-size

- src/pages/main-page.html
> Style/main page/btn

- src/pages/main-page.html
> 💄 style: Adjust btn margin,padding

- src/components/feed-card-item.html
- src/pages/feed-page.html
> :lipstick: style: Add shadow in feed-card-item

- src/components/feed-card-item.html
- src/pages/feed-page.html
> :lipstick: style: Adjust shadow in feed-card-item

- src/components/common-header.html
> :lipstick: style: Add transition color in nav anchor

- src/pages/main-page.html
> 💄 style: Adjust main-page header

- src/components/feed-card-item.html
- src/pages/feed-page.html
> :lipstick: style: Change shadow to border in feed-page

- src/pages/main-page.html
> 💄 style: Adjust main-page header duration

- src/pages/main-page.html
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #113
> 💄 style: Adjust main-page header padding-top

- .gitignore
- src/js/feed-page.js
> :sparkles: feat: Add link preview feature with API integration

- src/pages/login-page.html
- src/style.css
> ♻️ refactor: Update login-btn size

- src/pages/main-page.html
> ♻️ refactor: Update responsive UI design

- src/pages/main-page.html
> ♻️ refactor: Change Font-size

- src/pages/main-page.html
> Refactor/main page/all

- src/pages/main-page.html
- src/style.css
> 🖥 accessibility: Update heading structure and improve contrast ratio

- src/pages/login-page.html
> 💄 style: Update head favicon

- src/js/main-card-img.js
- src/js/main-card-item.js
- src/pages/main-page.html
> A11y/main page/validate

- src/js/project-page.js
> 🐛 fix: ensure edit modal uses flex display when shown

- src/js/common-header.js
> :sparkles: feat: Prevent link to mypage
